services:
  frontend:
    build:
      dockerfile: Dockerfile
      target: builder
      cache_from:
        - type=local,src=/tmp/.buildx-cache
      cache_to:
        - type=local,dest=/tmp/.buildx-cache-new,mode=max
